name: release
on: [workflow_dispatch, push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.CI_TOKEN }}
permissions:
  contents: 'write'
  pull-requests: 'write'
